apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: php:7.4-apache
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /var/www/html
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: webserver
