apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-ipnotics
  labels:
    app: web
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: iesgn/test_web:latest
        name: contendor-ipnotics
        ports:
        - name: http
          containerPort: 80
